import Link from 'next/link';
import React, { useEffect } from 'react';
import Aos from 'aos';
import "aos/dist/aos.css";
import {social} from "../info.config";
import ReactPlayer from 'react-player/youtube';

export default function Main() {
  useEffect(() => {
    Aos.init({ duration : 1500,
      offset: 100,
      delay : 500})
    }, []); 
    return(
    <div id="home"className='overflow-hidden flex flex-col items-center'>
        <div className="w-full h-screen flex flex-col items-center justify-center relative">
        <img
          src="/webimage2.png"
          className="w-screen object-cover"
        />
        <div className='mt-6 left-[40px] absolute flex flex-col'>

          <div className='flex flex-row items-center text-start'>
            <div className='mr-6  border-b-4 border-brand-yellow'>
                <h1 className='font-Kanit md:text-[60px] lg:text-[60px] text-[30px] text-white font-semibold uppercase'> Make your own story <br/>
                <span className='md:text-[75px] text-[35px] text-white'>IN <span className='bg-gradient-to-r from-amber-300 via-yellow-400 to-orange-500 bg-clip-text text-transparent'>DEXBATTLE</span></span></h1>
                <div className="md:flex justify-start mt-10 mb-[60px]">
             </div>
             </div>

            <div className='hidden lg:flex w-[600px] h-[600px] mt-[80px]'>
              <img src='webimage1.png'
              className='object-cover'/>
            </div>

          </div>
        </div>
        
        </div>

              
        <div data-aos ="fade-up"className='flex md:flex-row flex-col md:mx-16 justify-between bg-gray-700/40 backdrop-blur-sm rounded-lg items-center'>
          <div className='flex flex-col my-4 md:w-[70%] md:mx-10 mx-4'>
            <h1 data-aos="fade-right" className='md:text-5xl text-3xl font-Kanit text-white tracking-wide'>What is DexBattale?</h1>
            <h1 data-aos="fade-right" className='text-[18px] font-Kanit text-gray-400 text-justify mt-6'>
            Welcome to the ever-evolving Dex battle universe! Hone your shooting skills, compete in tournaments, and complete missions with your
Clan to earn NFTs and coveted rewards. Collect weapons, and so much more items. But most importantly, have fun and work together
Dex battle is a community-owned skill-based shooter with different PvP and PvE game modes for every type of player. The core shooter
game is set on top of a land control-oriented, social strategy game with a deep emphasis on clans, alliances, and social mechanics. The
game economy rewards social behavior and is designed to be an endless experience built by and for the player community.
Thus, Metaverse structures can be applied immensely in the Dex battle but it all depends on the player&apos;s feedback when the voting takes
place. Dex battle metaverse will bring the best experience ever when players combine a shooting skill-based game with a wisdom strategy
for each character. It is fun beyond the limit.
            </h1>

            <h1 data-aos="fade-up" className='text-3xl font-Kanit text-white tracking-wide mt-6'>Features</h1>
            <h1 data-aos="fade-up" className='text-[16px] font-Kanit text-gray-400 text-justify mt-4'>
            Dex battle features blockchain-based digital assets known as &ldquo;NFTs&ldquo; that operate on an eco-friendly proof-of-stake blockchain. Because
blockchain technology enables actual digital ownership, Dex battle characters may be exchanged not just on the specific Dex battle
marketplace, but also on a variety of other platforms. Given the massive trading volume and profits generated by these NFT markets, this
is a wonderful financial incentive for merely profit-driven users and a chance for next-generation green investment. With NFTs now
selling for millions of dollars, these fees may outweigh the revenue earned by in-game transactions.
            </h1>

          </div>

          <div className='w-full flex-row items-end'>
           <img
            data-aos="flip-up"
            src='/DexBattle PNG/DexBattle-nostore.jpg'
            className='md:mx-10 h-full w-full md:w-[70%] border border-gray-400 rounded-lg'/>

            </div>

           

        </div>

      </div>
    )
}
